### ISSUE TITLE
TensorFlow

### ISSUE THREAD

**Issue by solomonchak** [liyu95/DeepSimulator#43]
Hi,

Thanks for the great program. I installed it without error but got an error related to TenserFlow when I test it. Can you please help us?

> deep_simulator.sh -i chr4TE80%.fasta -c 8 -B 2 -D 1 -K 30 -M 0

Pre-process input genome...
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Pre-process input genome done!
Executing the preprocessing step...
('The average length is: ', 8032.0172451638146)
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Finished the preprocessing step!
Key parameters for simulation are shown below 
    event_std    : 1.0 
    filter_freq  : 950 
    signal_std   : 1.0 
Running the context-dependent pore model...
Traceback (most recent call last):
  File "/home/t/tchak/DeepSimulator/pore_model/src/context_simulator.py", line 2, in <module>
    from con_reg_seq import *
  File "/home/t/tchak/DeepSimulator/pore_model/src/con_reg_seq.py", line 3, in <module>
    import tensorflow as tf
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)

Failed to load the native TensorFlow runtime.
...

**Comment by liyu95** [comment]
Hi, thank you very much for your interest!
Could you please have a try to see if the given examples could be run or not? It would be easier for us to do the trouble-shooting.

**Comment by solomonchak** [comment]
Here's what I got when I used phage_lambda.fasta in the example folder. Thanks for helping!

(base) node219-45 DeepSimulator >: deep_simulator.sh -i ./example/phage_lambda.fasta -c 1 -B 2 -D 1 -K 30 -M 0

Pre-process input genome...
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Pre-process input genome done!
Executing the preprocessing step...
('The average length is: ', 8258.0441988950279)
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Finished the preprocessing step!
Key parameters for simulation are shown below 
    event_std    : 1.0 
    filter_freq  : 950 
    signal_std   : 1.0 
Running the context-dependent pore model...
Traceback (most recent call last):
  File "/home/t/tchak/DeepSimulator/pore_model/src/context_simulator.py", line 2, in <module>
    from con_reg_seq import *
  File "/home/t/tchak/DeepSimulator/pore_model/src/con_reg_seq.py", line 3, in <module>
    import tensorflow as tf
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /home/t/tchak/miniconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so)


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
DeprecationWarning: 'source deactivate' is deprecated. Use 'conda deactivate'.
Finished generate the simulated signals and fast5 files!
Running Basecalling...
   Basecalling with Guppy_CPU...
ONT Guppy basecalling software version 3.1.5+781ed57
config file:        /home/t/tchak/DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/dna_r9.4.1_450bps_hac.cfg
model file:         /home/t/tchak/DeepSimulator/base_caller/guppy_3.1.5/ont-guppy-cpu/data/template_r9.4.1_450bps_hac.jsn
input path:         /home/t/tchak/DeepSimulator/phage_lambda_DeepSimu/fast5
save path:          /home/t/tchak/DeepSimulator/phage_lambda_DeepSimu/fastq
chunk size:         1000
chunks per runner:  1000
records per file:   4000
num basecallers:    1
cpu mode:           ON
threads per caller: 1

Found 0 fast5 files to process.
Init time: 3568 ms

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
***************************************************
Caller time: 100 ms, Samples called: 0, samples/s: 0
Finishing up any open output files.
Basecalling completed successfully.
Basecalling finished!
Checking the read accuracy...
awk: fatal: division by zero attempted
Here is the mapping identity:  of 0 (pass 0 + fail 0) reads passed base-calling.
