### ISSUE TITLE
Error in pore_model.sh

### ISSUE THREAD

**Issue by Jenny-dan** [liyu95/DeepSimulator#44]
When I use example fasta files, it works well. However, when I use my fasta files, it comes to an error like this.
dzha@DESKTOP-4U9JHDU:/mnt/d/ape/Deepsimulator$ ./pore_model.sh ../test/random_a.fasta 1
  0%|                                                                                             | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/mnt/d/ape/Deepsimulator/pore_model/src/kmer_simulator.py", line 174, in <module>
    list(tqdm(p.imap(func, in_list),total=len(in_list)))
  File "/home/dzha/anaconda2/envs/tensorflow_cdpm/lib/python2.7/site-packages/tqdm/_tqdm.py", line 953, in __iter__
    for obj in iterable:
  File "/home/dzha/anaconda2/envs/tensorflow_cdpm/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
IOError: [Errno 2] No such file or directory: '/tmp/PORE_MODEL_random_a_7915_2020_07_26_21_41_47/signal_978b218d-1d53-4541-a44a-ca3a10d5bf2e runid=e4cf04589d9d6bebe247ec98452246ca2be9e293 read=32244 ch=335 start_time=2020-01-30T18:05:11Z flow_cell_id=FAL86920 protocol_group_id=yujing_4 sample_id=yujing_4_c47768a2-e458-4d97-ba23-88c7efeae661.fast5'

How can I solve this problem? Thanks!

**Comment by liyu95** [comment]
Hi, thank you very much for your interest!
It seems you got some path issues. Could you double-check when the files of each step are generated?
